import { ClientLogoWithSize } from "@/models/interfaces";

export const clientLogos: ClientLogoWithSize[] = [
  {
    name: "Yamaha",
    logo: "/images/logos/yamaha-logo.png",
    alt: "Yamaha Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Sony",
    logo: "/images/logos/sony-logo.png",
    alt: "Sony Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Shure",
    logo: "/images/logos/shure-logo.png",
    alt: "Shure Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Sennheiser",
    logo: "/images/logos/sennheiser-logo.png",
    alt: "Sennheiser Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Samsung",
    logo: "/images/logos/samsung-logo.png",
    alt: "Samsung Logo",
    width: 160,
    height: 100,
  },
  {
    name: "QSC",
    logo: "/images/logos/qsc-logo.png",
    alt: "QSC Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Panasonic",
    logo: "/images/logos/panasonic-logo.png",
    alt: "Panasonic Logo",
    width: 160,
    height: 100,
  },
  {
    name: "JBL",
    logo: "/images/logos/jbl-logo.png",
    alt: "JBL Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Extron",
    logo: "/images/logos/extron-log.png",
    alt: "Extron Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Crestron",
    logo: "/images/logos/crestron-logo.png",
    alt: "Crestron Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Bose",
    logo: "/images/logos/bose-logo.png",
    alt: "Bose Logo",
    width: 160,
    height: 100,
  },
  // Duplicate entries for longer carousel effect
  {
    name: "Yamaha",
    logo: "/images/logos/yamaha-logo.png",
    alt: "Yamaha Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Sony",
    logo: "/images/logos/sony-logo.png",
    alt: "Sony Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Shure",
    logo: "/images/logos/shure-logo.png",
    alt: "Shure Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Sennheiser",
    logo: "/images/logos/sennheiser-logo.png",
    alt: "Sennheiser Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Samsung",
    logo: "/images/logos/samsung-logo.png",
    alt: "Samsung Logo",
    width: 160,
    height: 100,
  },
  {
    name: "QSC",
    logo: "/images/logos/qsc-logo.png",
    alt: "QSC Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Panasonic",
    logo: "/images/logos/panasonic-logo.png",
    alt: "Panasonic Logo",
    width: 160,
    height: 100,
  },
  {
    name: "JBL",
    logo: "/images/logos/jbl-logo.png",
    alt: "JBL Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Extron",
    logo: "/images/logos/extron-log.png",
    alt: "Extron Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Crestron",
    logo: "/images/logos/crestron-logo.png",
    alt: "Crestron Logo",
    width: 160,
    height: 100,
  },
  {
    name: "Bose",
    logo: "/images/logos/bose-logo.png",
    alt: "Bose Logo",
    width: 160,
    height: 100,
  },
];
